defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${dir.output_dir}/ckpts
  filename: "epoch_{epoch:03d}"
  monitor: "val_loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "competition_metrics"
  patience: 100 # early stoppingをしない場合は大きな値を設定
  mode: "max"

model_summary:
  max_depth: 1
