defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${dir.output_dir}/${exp_name}
  filename: "epoch_{epoch:03d}"
  monitor: "val_loss"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val_loss"
  patience: 100
  mode: "max"

model_summary:
  max_depth: 1
