# @package _global_
# overriding hydra default config
hydra:
  job:
    name: train
  run:
    dir: ${dir.output_dir}/${exp_name}

defaults:
  - _self_
  - trainer: basic_trainer
  - model: basic_model
  - dataset: basic_dataset
  - dir: basic_dir

competition_name: mnist
seed: 42
exp_name: default
ckpt_path: null
